name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean with Make
      run: make clean
    - name: Build with Make
      run: make test
    - name: Build the program with error
      run: make run

