name: C/C++ CI

on:
  push:
    branches: [ "main", "09-04-2025 ---- Cmassong-#1" ]
  pull_request:
    branches: [ "main", "09-04-2025 ---- Cmassong-#1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with Make
      run: make
    - name: Run tests
      run: make check
